### PR TITLE
LanguageConfiguration: expose most helpers

### PR DESCRIPTION
**Pull request by mchakravarty**
They get scoped and slightly more expressive names. (The names are still partially abbreviated; otherwise, the regular expressions just get too big, negatively affecting readability.)

### CODE REVIEW

**Comment by frios** [comment]
I have incorporated this PR into my code. When I build my LanguageCoonfiguration extension, i get an error:

'LanguageConfiguration' initializer is inaccessible due to 'internal' protection level

Also get an error in GutterView.swift line 294:

Cannot call value of non-function type 'Theme'

**Comment by mchakravarty** [comment]
> I have incorporated this PR into my code. When I build my LanguageCoonfiguration extension, i get an error:
> 
> 'LanguageConfiguration' initializer is inaccessible due to 'internal' protection level

Thanks, I forgot to add a public initialiser.
 
> Also get an error in GutterView.swift line 294:
> 
> Cannot call value of non-function type 'Theme'

Sorry, after making the changes, I only tried compiling this branch on macOS and not iOS.

Both issues ought to be fixed by the last commit in this PR.

**Comment by frios** [comment]
Great. I will give it a try!

**Comment by frios** [comment]
This is working well. I need to familiarize myself with the source code better, but it is looking good. Thanks for the help. You might want to merge this with you main branch now.

**Comment by mchakravarty** [comment]
> This is working well. I need to familiarize myself with the source code better, but it is looking good. Thanks for the help. You might want to merge this with you main branch now.

Good to hear. I will merge it now.

**Pull request merged**
