### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CrashdebugDevelopment**

### CODE REVIEW

**Comment by mchakravarty** [comment]
@CrashdebugDevelopment Thanks!

**Comment by CrashdebugDevelopment** [comment]
No problem! I just figured I edit that in, because I got confused because I didn't know that language support existed...

**Comment by mchakravarty** [comment]
Yeah, good point.

**Comment by CrashdebugDevelopment** [comment]
@mchakravarty can you help me with my code?

**Pull request merged**
