### PR TITLE
Add an SQLite language configuration

### PR DESCRIPTION
**Pull request by barnettben**
Here's my first pass at creating an SQLite language configuration (see #116). It includes tests, and I hope it's OK, but I've used Swift Testing for these new tests so as to be able to use parameterised tests.

It broadly works, but I'm having a bit of trouble with the regex for negative numbers. You'll see the number tokenising test fail on these cases.

The leading `-` is always tokenised separately. I believe this to be the case for the Swift language configuration as well. 

I've experimented with [swiftregex.com](swiftregex.com) and on there negative numbers are matched if I replace the negation part `/(?:\B-|\b)/` with `Optionally("-")`. But when I put that back into the language config, the leading `-` is still matched separately.

If anyone's open to having a look at this, I'd be grateful for any assistance.

### CODE REVIEW

**Comment by mchakravarty** [comment]
Concerning the tokenisation of negative numbers, it really depends a bit on the precise syntax of the language under consideration. Some languages do require to parse a leading `-` as a unary operator, instead of being part of the number literal. I don't know how SQLite defines it, but that ought to be specified in the language reference.

My guess for the current behaviour would be that there is a conflict between the reserved operator `-` and the leading `-` in a negative number.

**Comment by barnettben** [comment]
Thank you, I hadn't thought of that. For my needs, removing the leading `-` from the numbers would probably be good enough. If you're happy to accept that, I can remove it from the regex definitions and submit the PR properly.

**Comment by barnettben** [comment]
I've had a closer look, and the current behaviour does seem to match the info in the link above, so I've updated the tests to match this and added a link to the docs.

**Comment by mchakravarty** [comment]
Looks good! Thanks a lot!

**Pull request merged**
